package main

import (
	"ai_agents/agile_meth/config"
	"ai_agents/agile_meth/ai_model/assistants"
	"ai_agents/agile_meth/planning"
	"fmt"
)

func main() {
	c := config.NewModelConfigs()["gpt4"]
	on := assistants.NewOpenAI(c.ApiKey, c.AssistUrl, c.ThreadUrl, c.Model)
	// Create instances of team members
	// Developer_John := development.NewDeveloper("John", on)
	sm := planning.NewAgileProject("ScrumMaster", on)

    // vision := `Our Vision: Build a world wide game that millions around the world could play in the virtual environment generated by AI
	// Adopt Agile methodology and step by step code by code session by session implement the game using agile methodology.`
	vision := `Implement a VectorDB for my generative AI application`
    questions := sm.VisionClarification(vision)
    // goals := sm.BreakDownVision(vision)
    // fmt.Printf("Vision: %s \n\n", sm.Vision)
    // for k, v := range goals{
    //     fmt.Printf("Goal%d: %s: %s \n", k+1, v.Goal, v.Reason)
    // }
    for k, v := range questions{
        fmt.Printf("Question%d: %s: %s \n", k+1, v.Question, v.Concept)
    }
	// tester.WorkOn(userStory)
	// designer.WorkOn(userStory)
}
